name: Ginger GM TV
favicon: null
layout_spectrum: 0.5525421451311558
typography_spectrum: 0.6268074761610478
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6802698338869959
  lightness: 0.699753136606887
  saturation: 0.7727229124866426
  rhythmicContrast: 0.11381699214689434
purpose: []
