name: Ginger GM TV
favicon: null
layout_spectrum: 0.5525421451311558
typography_spectrum: 0.6268074761610478
title: Chess Videos from Grandmaster Simon Williams
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f99621'
    - '#feedd9'
    - '#ffd19d'
    - '#f9aa4e'
  brandStrength: 0.8125
  lightness: 0.699753136606887
  saturation: 0.7727229124866426
  rhythmicContrast: 0.11381699214689434
purpose: []
