name: Ginger GM TV
favicon: null
layout_spectrum: 0.39647
typography_spectrum: 0.36091
title: Chess Videos from Grandmaster Simon Williams
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7941d'
    - '#ffffff'
    - '#000000'
    - '#905002'
    - '#402e0c'
  brandStrength: 0.25
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
